server:
  port: 8080

spring:
  application:
    name: money-transfer-service

logging:
  format: "{timestamp} | From: {cardFrom} | To: {cardTo} | Amount: {amount} {currency} | Commission: {commission} | Status: {status} | OperationID: {operationId}"